/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Agent } from './Agent';
import {
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
    AgentToJSONTyped,
} from './Agent';
import type { Contract } from './Contract';
import {
    ContractFromJSON,
    ContractFromJSONTyped,
    ContractToJSON,
    ContractToJSONTyped,
} from './Contract';

/**
 * 
 * @export
 * @interface AcceptContract200ResponseData
 */
export interface AcceptContract200ResponseData {
    /**
     * 
     * @type {Agent}
     * @memberof AcceptContract200ResponseData
     */
    agent: Agent;
    /**
     * 
     * @type {Contract}
     * @memberof AcceptContract200ResponseData
     */
    contract: Contract;
}

/**
 * Check if a given object implements the AcceptContract200ResponseData interface.
 */
export function instanceOfAcceptContract200ResponseData(value: object): value is AcceptContract200ResponseData {
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    return true;
}

export function AcceptContract200ResponseDataFromJSON(json: any): AcceptContract200ResponseData {
    return AcceptContract200ResponseDataFromJSONTyped(json, false);
}

export function AcceptContract200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptContract200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'agent': AgentFromJSON(json['agent']),
        'contract': ContractFromJSON(json['contract']),
    };
}

export function AcceptContract200ResponseDataToJSON(json: any): AcceptContract200ResponseData {
    return AcceptContract200ResponseDataToJSONTyped(json, false);
}

export function AcceptContract200ResponseDataToJSONTyped(value?: AcceptContract200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent': AgentToJSON(value['agent']),
        'contract': ContractToJSON(value['contract']),
    };
}

