/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Agent details.
 * @export
 * @interface Agent
 */
export interface Agent {
    /**
     * Account ID that is tied to this agent. Only included on your own agent.
     * @type {string}
     * @memberof Agent
     */
    accountId?: string;
    /**
     * Symbol of the agent.
     * @type {string}
     * @memberof Agent
     */
    symbol: string;
    /**
     * The headquarters of the agent.
     * @type {string}
     * @memberof Agent
     */
    headquarters: string;
    /**
     * The number of credits the agent has available. Credits can be negative if funds have been overdrawn.
     * @type {number}
     * @memberof Agent
     */
    credits: number;
    /**
     * The faction the agent started with.
     * @type {string}
     * @memberof Agent
     */
    startingFaction: string;
    /**
     * How many ships are owned by the agent.
     * @type {number}
     * @memberof Agent
     */
    shipCount: number;
}

/**
 * Check if a given object implements the Agent interface.
 */
export function instanceOfAgent(value: object): value is Agent {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('headquarters' in value) || value['headquarters'] === undefined) return false;
    if (!('credits' in value) || value['credits'] === undefined) return false;
    if (!('startingFaction' in value) || value['startingFaction'] === undefined) return false;
    if (!('shipCount' in value) || value['shipCount'] === undefined) return false;
    return true;
}

export function AgentFromJSON(json: any): Agent {
    return AgentFromJSONTyped(json, false);
}

export function AgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Agent {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'symbol': json['symbol'],
        'headquarters': json['headquarters'],
        'credits': json['credits'],
        'startingFaction': json['startingFaction'],
        'shipCount': json['shipCount'],
    };
}

export function AgentToJSON(json: any): Agent {
    return AgentToJSONTyped(json, false);
}

export function AgentToJSONTyped(value?: Agent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'symbol': value['symbol'],
        'headquarters': value['headquarters'],
        'credits': value['credits'],
        'startingFaction': value['startingFaction'],
        'shipCount': value['shipCount'],
    };
}

