/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScrapTransaction } from './ScrapTransaction';
import {
    ScrapTransactionFromJSON,
    ScrapTransactionFromJSONTyped,
    ScrapTransactionToJSON,
    ScrapTransactionToJSONTyped,
} from './ScrapTransaction';

/**
 * 
 * @export
 * @interface GetScrapShip200ResponseData
 */
export interface GetScrapShip200ResponseData {
    /**
     * 
     * @type {ScrapTransaction}
     * @memberof GetScrapShip200ResponseData
     */
    transaction: ScrapTransaction;
}

/**
 * Check if a given object implements the GetScrapShip200ResponseData interface.
 */
export function instanceOfGetScrapShip200ResponseData(value: object): value is GetScrapShip200ResponseData {
    if (!('transaction' in value) || value['transaction'] === undefined) return false;
    return true;
}

export function GetScrapShip200ResponseDataFromJSON(json: any): GetScrapShip200ResponseData {
    return GetScrapShip200ResponseDataFromJSONTyped(json, false);
}

export function GetScrapShip200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetScrapShip200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction': ScrapTransactionFromJSON(json['transaction']),
    };
}

export function GetScrapShip200ResponseDataToJSON(json: any): GetScrapShip200ResponseData {
    return GetScrapShip200ResponseDataToJSONTyped(json, false);
}

export function GetScrapShip200ResponseDataToJSONTyped(value?: GetScrapShip200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction': ScrapTransactionToJSON(value['transaction']),
    };
}

