/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetStatus200ResponseLeaderboardsMostSubmittedChartsInner } from './GetStatus200ResponseLeaderboardsMostSubmittedChartsInner';
import {
    GetStatus200ResponseLeaderboardsMostSubmittedChartsInnerFromJSON,
    GetStatus200ResponseLeaderboardsMostSubmittedChartsInnerFromJSONTyped,
    GetStatus200ResponseLeaderboardsMostSubmittedChartsInnerToJSON,
    GetStatus200ResponseLeaderboardsMostSubmittedChartsInnerToJSONTyped,
} from './GetStatus200ResponseLeaderboardsMostSubmittedChartsInner';
import type { GetStatus200ResponseLeaderboardsMostCreditsInner } from './GetStatus200ResponseLeaderboardsMostCreditsInner';
import {
    GetStatus200ResponseLeaderboardsMostCreditsInnerFromJSON,
    GetStatus200ResponseLeaderboardsMostCreditsInnerFromJSONTyped,
    GetStatus200ResponseLeaderboardsMostCreditsInnerToJSON,
    GetStatus200ResponseLeaderboardsMostCreditsInnerToJSONTyped,
} from './GetStatus200ResponseLeaderboardsMostCreditsInner';

/**
 * 
 * @export
 * @interface GetStatus200ResponseLeaderboards
 */
export interface GetStatus200ResponseLeaderboards {
    /**
     * Top agents with the most credits.
     * @type {Array<GetStatus200ResponseLeaderboardsMostCreditsInner>}
     * @memberof GetStatus200ResponseLeaderboards
     */
    mostCredits: Array<GetStatus200ResponseLeaderboardsMostCreditsInner>;
    /**
     * Top agents with the most charted submitted.
     * @type {Array<GetStatus200ResponseLeaderboardsMostSubmittedChartsInner>}
     * @memberof GetStatus200ResponseLeaderboards
     */
    mostSubmittedCharts: Array<GetStatus200ResponseLeaderboardsMostSubmittedChartsInner>;
}

/**
 * Check if a given object implements the GetStatus200ResponseLeaderboards interface.
 */
export function instanceOfGetStatus200ResponseLeaderboards(value: object): value is GetStatus200ResponseLeaderboards {
    if (!('mostCredits' in value) || value['mostCredits'] === undefined) return false;
    if (!('mostSubmittedCharts' in value) || value['mostSubmittedCharts'] === undefined) return false;
    return true;
}

export function GetStatus200ResponseLeaderboardsFromJSON(json: any): GetStatus200ResponseLeaderboards {
    return GetStatus200ResponseLeaderboardsFromJSONTyped(json, false);
}

export function GetStatus200ResponseLeaderboardsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatus200ResponseLeaderboards {
    if (json == null) {
        return json;
    }
    return {
        
        'mostCredits': ((json['mostCredits'] as Array<any>).map(GetStatus200ResponseLeaderboardsMostCreditsInnerFromJSON)),
        'mostSubmittedCharts': ((json['mostSubmittedCharts'] as Array<any>).map(GetStatus200ResponseLeaderboardsMostSubmittedChartsInnerFromJSON)),
    };
}

export function GetStatus200ResponseLeaderboardsToJSON(json: any): GetStatus200ResponseLeaderboards {
    return GetStatus200ResponseLeaderboardsToJSONTyped(json, false);
}

export function GetStatus200ResponseLeaderboardsToJSONTyped(value?: GetStatus200ResponseLeaderboards | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mostCredits': ((value['mostCredits'] as Array<any>).map(GetStatus200ResponseLeaderboardsMostCreditsInnerToJSON)),
        'mostSubmittedCharts': ((value['mostSubmittedCharts'] as Array<any>).map(GetStatus200ResponseLeaderboardsMostSubmittedChartsInnerToJSON)),
    };
}

