/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TradeSymbol } from './TradeSymbol';
import {
    TradeSymbolFromJSON,
    TradeSymbolFromJSONTyped,
    TradeSymbolToJSON,
    TradeSymbolToJSONTyped,
} from './TradeSymbol';

/**
 * 
 * @export
 * @interface JettisonRequest
 */
export interface JettisonRequest {
    /**
     * 
     * @type {TradeSymbol}
     * @memberof JettisonRequest
     */
    symbol: TradeSymbol;
    /**
     * Amount of units to jettison of this good.
     * @type {number}
     * @memberof JettisonRequest
     */
    units: number;
}



/**
 * Check if a given object implements the JettisonRequest interface.
 */
export function instanceOfJettisonRequest(value: object): value is JettisonRequest {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('units' in value) || value['units'] === undefined) return false;
    return true;
}

export function JettisonRequestFromJSON(json: any): JettisonRequest {
    return JettisonRequestFromJSONTyped(json, false);
}

export function JettisonRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JettisonRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': TradeSymbolFromJSON(json['symbol']),
        'units': json['units'],
    };
}

export function JettisonRequestToJSON(json: any): JettisonRequest {
    return JettisonRequestToJSONTyped(json, false);
}

export function JettisonRequestToJSONTyped(value?: JettisonRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': TradeSymbolToJSON(value['symbol']),
        'units': value['units'],
    };
}

