/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Jettison200ResponseData } from './Jettison200ResponseData';
import {
    Jettison200ResponseDataFromJSON,
    Jettison200ResponseDataFromJSONTyped,
    Jettison200ResponseDataToJSON,
    Jettison200ResponseDataToJSONTyped,
} from './Jettison200ResponseData';

/**
 * 
 * @export
 * @interface Jettison200Response
 */
export interface Jettison200Response {
    /**
     * 
     * @type {Jettison200ResponseData}
     * @memberof Jettison200Response
     */
    data: Jettison200ResponseData;
}

/**
 * Check if a given object implements the Jettison200Response interface.
 */
export function instanceOfJettison200Response(value: object): value is Jettison200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function Jettison200ResponseFromJSON(json: any): Jettison200Response {
    return Jettison200ResponseFromJSONTyped(json, false);
}

export function Jettison200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Jettison200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': Jettison200ResponseDataFromJSON(json['data']),
    };
}

export function Jettison200ResponseToJSON(json: any): Jettison200Response {
    return Jettison200ResponseToJSONTyped(json, false);
}

export function Jettison200ResponseToJSONTyped(value?: Jettison200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': Jettison200ResponseDataToJSON(value['data']),
    };
}

