/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NavigateShipRequest
 */
export interface NavigateShipRequest {
    /**
     * The target destination.
     * @type {string}
     * @memberof NavigateShipRequest
     */
    waypointSymbol: string;
}

/**
 * Check if a given object implements the NavigateShipRequest interface.
 */
export function instanceOfNavigateShipRequest(value: object): value is NavigateShipRequest {
    if (!('waypointSymbol' in value) || value['waypointSymbol'] === undefined) return false;
    return true;
}

export function NavigateShipRequestFromJSON(json: any): NavigateShipRequest {
    return NavigateShipRequestFromJSONTyped(json, false);
}

export function NavigateShipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NavigateShipRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'waypointSymbol': json['waypointSymbol'],
    };
}

export function NavigateShipRequestToJSON(json: any): NavigateShipRequest {
    return NavigateShipRequestToJSONTyped(json, false);
}

export function NavigateShipRequestToJSONTyped(value?: NavigateShipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'waypointSymbol': value['waypointSymbol'],
    };
}

