/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NegotiateContract200ResponseData } from './NegotiateContract200ResponseData';
import {
    NegotiateContract200ResponseDataFromJSON,
    NegotiateContract200ResponseDataFromJSONTyped,
    NegotiateContract200ResponseDataToJSON,
    NegotiateContract200ResponseDataToJSONTyped,
} from './NegotiateContract200ResponseData';

/**
 * 
 * @export
 * @interface NegotiateContract200Response
 */
export interface NegotiateContract200Response {
    /**
     * 
     * @type {NegotiateContract200ResponseData}
     * @memberof NegotiateContract200Response
     */
    data: NegotiateContract200ResponseData;
}

/**
 * Check if a given object implements the NegotiateContract200Response interface.
 */
export function instanceOfNegotiateContract200Response(value: object): value is NegotiateContract200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NegotiateContract200ResponseFromJSON(json: any): NegotiateContract200Response {
    return NegotiateContract200ResponseFromJSONTyped(json, false);
}

export function NegotiateContract200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NegotiateContract200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NegotiateContract200ResponseDataFromJSON(json['data']),
    };
}

export function NegotiateContract200ResponseToJSON(json: any): NegotiateContract200Response {
    return NegotiateContract200ResponseToJSONTyped(json, false);
}

export function NegotiateContract200ResponseToJSONTyped(value?: NegotiateContract200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NegotiateContract200ResponseDataToJSON(value['data']),
    };
}

