/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Agent } from './Agent';
import {
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
    AgentToJSONTyped,
} from './Agent';
import type { ShipCargo } from './ShipCargo';
import {
    ShipCargoFromJSON,
    ShipCargoFromJSONTyped,
    ShipCargoToJSON,
    ShipCargoToJSONTyped,
} from './ShipCargo';
import type { ShipMount } from './ShipMount';
import {
    ShipMountFromJSON,
    ShipMountFromJSONTyped,
    ShipMountToJSON,
    ShipMountToJSONTyped,
} from './ShipMount';
import type { ShipModificationTransaction } from './ShipModificationTransaction';
import {
    ShipModificationTransactionFromJSON,
    ShipModificationTransactionFromJSONTyped,
    ShipModificationTransactionToJSON,
    ShipModificationTransactionToJSONTyped,
} from './ShipModificationTransaction';

/**
 * 
 * @export
 * @interface RemoveMount201ResponseData
 */
export interface RemoveMount201ResponseData {
    /**
     * 
     * @type {Agent}
     * @memberof RemoveMount201ResponseData
     */
    agent: Agent;
    /**
     * List of installed mounts after the removal of the selected mount.
     * @type {Array<ShipMount>}
     * @memberof RemoveMount201ResponseData
     */
    mounts: Array<ShipMount>;
    /**
     * 
     * @type {ShipCargo}
     * @memberof RemoveMount201ResponseData
     */
    cargo: ShipCargo;
    /**
     * 
     * @type {ShipModificationTransaction}
     * @memberof RemoveMount201ResponseData
     */
    transaction: ShipModificationTransaction;
}

/**
 * Check if a given object implements the RemoveMount201ResponseData interface.
 */
export function instanceOfRemoveMount201ResponseData(value: object): value is RemoveMount201ResponseData {
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('mounts' in value) || value['mounts'] === undefined) return false;
    if (!('cargo' in value) || value['cargo'] === undefined) return false;
    if (!('transaction' in value) || value['transaction'] === undefined) return false;
    return true;
}

export function RemoveMount201ResponseDataFromJSON(json: any): RemoveMount201ResponseData {
    return RemoveMount201ResponseDataFromJSONTyped(json, false);
}

export function RemoveMount201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveMount201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'agent': AgentFromJSON(json['agent']),
        'mounts': ((json['mounts'] as Array<any>).map(ShipMountFromJSON)),
        'cargo': ShipCargoFromJSON(json['cargo']),
        'transaction': ShipModificationTransactionFromJSON(json['transaction']),
    };
}

export function RemoveMount201ResponseDataToJSON(json: any): RemoveMount201ResponseData {
    return RemoveMount201ResponseDataToJSONTyped(json, false);
}

export function RemoveMount201ResponseDataToJSONTyped(value?: RemoveMount201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent': AgentToJSON(value['agent']),
        'mounts': ((value['mounts'] as Array<any>).map(ShipMountToJSON)),
        'cargo': ShipCargoToJSON(value['cargo']),
        'transaction': ShipModificationTransactionToJSON(value['transaction']),
    };
}

