/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WaypointTrait } from './WaypointTrait';
import {
    WaypointTraitFromJSON,
    WaypointTraitFromJSONTyped,
    WaypointTraitToJSON,
    WaypointTraitToJSONTyped,
} from './WaypointTrait';
import type { WaypointOrbital } from './WaypointOrbital';
import {
    WaypointOrbitalFromJSON,
    WaypointOrbitalFromJSONTyped,
    WaypointOrbitalToJSON,
    WaypointOrbitalToJSONTyped,
} from './WaypointOrbital';
import type { WaypointType } from './WaypointType';
import {
    WaypointTypeFromJSON,
    WaypointTypeFromJSONTyped,
    WaypointTypeToJSON,
    WaypointTypeToJSONTyped,
} from './WaypointType';
import type { WaypointFaction } from './WaypointFaction';
import {
    WaypointFactionFromJSON,
    WaypointFactionFromJSONTyped,
    WaypointFactionToJSON,
    WaypointFactionToJSONTyped,
} from './WaypointFaction';
import type { Chart } from './Chart';
import {
    ChartFromJSON,
    ChartFromJSONTyped,
    ChartToJSON,
    ChartToJSONTyped,
} from './Chart';

/**
 * A waypoint that was scanned by a ship.
 * @export
 * @interface ScannedWaypoint
 */
export interface ScannedWaypoint {
    /**
     * The symbol of the waypoint.
     * @type {string}
     * @memberof ScannedWaypoint
     */
    symbol: string;
    /**
     * 
     * @type {WaypointType}
     * @memberof ScannedWaypoint
     */
    type: WaypointType;
    /**
     * The symbol of the system.
     * @type {string}
     * @memberof ScannedWaypoint
     */
    systemSymbol: string;
    /**
     * Position in the universe in the x axis.
     * @type {number}
     * @memberof ScannedWaypoint
     */
    x: number;
    /**
     * Position in the universe in the y axis.
     * @type {number}
     * @memberof ScannedWaypoint
     */
    y: number;
    /**
     * List of waypoints that orbit this waypoint.
     * @type {Array<WaypointOrbital>}
     * @memberof ScannedWaypoint
     */
    orbitals: Array<WaypointOrbital>;
    /**
     * 
     * @type {WaypointFaction}
     * @memberof ScannedWaypoint
     */
    faction?: WaypointFaction;
    /**
     * The traits of the waypoint.
     * @type {Array<WaypointTrait>}
     * @memberof ScannedWaypoint
     */
    traits: Array<WaypointTrait>;
    /**
     * 
     * @type {Chart}
     * @memberof ScannedWaypoint
     */
    chart?: Chart;
}



/**
 * Check if a given object implements the ScannedWaypoint interface.
 */
export function instanceOfScannedWaypoint(value: object): value is ScannedWaypoint {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('systemSymbol' in value) || value['systemSymbol'] === undefined) return false;
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    if (!('orbitals' in value) || value['orbitals'] === undefined) return false;
    if (!('traits' in value) || value['traits'] === undefined) return false;
    return true;
}

export function ScannedWaypointFromJSON(json: any): ScannedWaypoint {
    return ScannedWaypointFromJSONTyped(json, false);
}

export function ScannedWaypointFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScannedWaypoint {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'type': WaypointTypeFromJSON(json['type']),
        'systemSymbol': json['systemSymbol'],
        'x': json['x'],
        'y': json['y'],
        'orbitals': ((json['orbitals'] as Array<any>).map(WaypointOrbitalFromJSON)),
        'faction': json['faction'] == null ? undefined : WaypointFactionFromJSON(json['faction']),
        'traits': ((json['traits'] as Array<any>).map(WaypointTraitFromJSON)),
        'chart': json['chart'] == null ? undefined : ChartFromJSON(json['chart']),
    };
}

export function ScannedWaypointToJSON(json: any): ScannedWaypoint {
    return ScannedWaypointToJSONTyped(json, false);
}

export function ScannedWaypointToJSONTyped(value?: ScannedWaypoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
        'type': WaypointTypeToJSON(value['type']),
        'systemSymbol': value['systemSymbol'],
        'x': value['x'],
        'y': value['y'],
        'orbitals': ((value['orbitals'] as Array<any>).map(WaypointOrbitalToJSON)),
        'faction': WaypointFactionToJSON(value['faction']),
        'traits': ((value['traits'] as Array<any>).map(WaypointTraitToJSON)),
        'chart': ChartToJSON(value['chart']),
    };
}

