/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShipyardShipCrew
 */
export interface ShipyardShipCrew {
    /**
     * 
     * @type {number}
     * @memberof ShipyardShipCrew
     */
    required: number;
    /**
     * 
     * @type {number}
     * @memberof ShipyardShipCrew
     */
    capacity: number;
}

/**
 * Check if a given object implements the ShipyardShipCrew interface.
 */
export function instanceOfShipyardShipCrew(value: object): value is ShipyardShipCrew {
    if (!('required' in value) || value['required'] === undefined) return false;
    if (!('capacity' in value) || value['capacity'] === undefined) return false;
    return true;
}

export function ShipyardShipCrewFromJSON(json: any): ShipyardShipCrew {
    return ShipyardShipCrewFromJSONTyped(json, false);
}

export function ShipyardShipCrewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipyardShipCrew {
    if (json == null) {
        return json;
    }
    return {
        
        'required': json['required'],
        'capacity': json['capacity'],
    };
}

export function ShipyardShipCrewToJSON(json: any): ShipyardShipCrew {
    return ShipyardShipCrewToJSONTyped(json, false);
}

export function ShipyardShipCrewToJSONTyped(value?: ShipyardShipCrew | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'required': value['required'],
        'capacity': value['capacity'],
    };
}

