/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Siphon } from './Siphon';
import {
    SiphonFromJSON,
    SiphonFromJSONTyped,
    SiphonToJSON,
    SiphonToJSONTyped,
} from './Siphon';
import type { ShipCargo } from './ShipCargo';
import {
    ShipCargoFromJSON,
    ShipCargoFromJSONTyped,
    ShipCargoToJSON,
    ShipCargoToJSONTyped,
} from './ShipCargo';
import type { Cooldown } from './Cooldown';
import {
    CooldownFromJSON,
    CooldownFromJSONTyped,
    CooldownToJSON,
    CooldownToJSONTyped,
} from './Cooldown';
import type { ShipConditionEvent } from './ShipConditionEvent';
import {
    ShipConditionEventFromJSON,
    ShipConditionEventFromJSONTyped,
    ShipConditionEventToJSON,
    ShipConditionEventToJSONTyped,
} from './ShipConditionEvent';

/**
 * 
 * @export
 * @interface SiphonResources201ResponseData
 */
export interface SiphonResources201ResponseData {
    /**
     * 
     * @type {Cooldown}
     * @memberof SiphonResources201ResponseData
     */
    cooldown: Cooldown;
    /**
     * 
     * @type {Siphon}
     * @memberof SiphonResources201ResponseData
     */
    siphon: Siphon;
    /**
     * 
     * @type {ShipCargo}
     * @memberof SiphonResources201ResponseData
     */
    cargo: ShipCargo;
    /**
     * 
     * @type {Array<ShipConditionEvent>}
     * @memberof SiphonResources201ResponseData
     */
    events: Array<ShipConditionEvent>;
}

/**
 * Check if a given object implements the SiphonResources201ResponseData interface.
 */
export function instanceOfSiphonResources201ResponseData(value: object): value is SiphonResources201ResponseData {
    if (!('cooldown' in value) || value['cooldown'] === undefined) return false;
    if (!('siphon' in value) || value['siphon'] === undefined) return false;
    if (!('cargo' in value) || value['cargo'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function SiphonResources201ResponseDataFromJSON(json: any): SiphonResources201ResponseData {
    return SiphonResources201ResponseDataFromJSONTyped(json, false);
}

export function SiphonResources201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiphonResources201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'cooldown': CooldownFromJSON(json['cooldown']),
        'siphon': SiphonFromJSON(json['siphon']),
        'cargo': ShipCargoFromJSON(json['cargo']),
        'events': ((json['events'] as Array<any>).map(ShipConditionEventFromJSON)),
    };
}

export function SiphonResources201ResponseDataToJSON(json: any): SiphonResources201ResponseData {
    return SiphonResources201ResponseDataToJSONTyped(json, false);
}

export function SiphonResources201ResponseDataToJSONTyped(value?: SiphonResources201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cooldown': CooldownToJSON(value['cooldown']),
        'siphon': SiphonToJSON(value['siphon']),
        'cargo': ShipCargoToJSON(value['cargo']),
        'events': ((value['events'] as Array<any>).map(ShipConditionEventToJSON)),
    };
}

