/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShipFuel } from './ShipFuel';
import {
    ShipFuelFromJSON,
    ShipFuelFromJSONTyped,
    ShipFuelToJSON,
    ShipFuelToJSONTyped,
} from './ShipFuel';
import type { ShipNav } from './ShipNav';
import {
    ShipNavFromJSON,
    ShipNavFromJSONTyped,
    ShipNavToJSON,
    ShipNavToJSONTyped,
} from './ShipNav';

/**
 * 
 * @export
 * @interface WarpShip200ResponseData
 */
export interface WarpShip200ResponseData {
    /**
     * 
     * @type {ShipFuel}
     * @memberof WarpShip200ResponseData
     */
    fuel: ShipFuel;
    /**
     * 
     * @type {ShipNav}
     * @memberof WarpShip200ResponseData
     */
    nav: ShipNav;
}

/**
 * Check if a given object implements the WarpShip200ResponseData interface.
 */
export function instanceOfWarpShip200ResponseData(value: object): value is WarpShip200ResponseData {
    if (!('fuel' in value) || value['fuel'] === undefined) return false;
    if (!('nav' in value) || value['nav'] === undefined) return false;
    return true;
}

export function WarpShip200ResponseDataFromJSON(json: any): WarpShip200ResponseData {
    return WarpShip200ResponseDataFromJSONTyped(json, false);
}

export function WarpShip200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WarpShip200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'fuel': ShipFuelFromJSON(json['fuel']),
        'nav': ShipNavFromJSON(json['nav']),
    };
}

export function WarpShip200ResponseDataToJSON(json: any): WarpShip200ResponseData {
    return WarpShip200ResponseDataToJSONTyped(json, false);
}

export function WarpShip200ResponseDataToJSONTyped(value?: WarpShip200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fuel': ShipFuelToJSON(value['fuel']),
        'nav': ShipNavToJSON(value['nav']),
    };
}

